### ISSUE TITLE
Support for pyyaml==6.0.1

### ISSUE THREAD

**Issue by smsajjadzaidi** [abn/cafeteria#173]
Pyyaml==5.4.1 is failing to build because of some updates in cython. They have released a new version i.e. 6.0.1 which resolves this issue but cafeteria requires pyyaml<6.0 which is why I am unable to update pyyaml in my dependencies. Can we update pyyaml to work with pyyaml 6.0.1 please?

reference: https://github.com/yaml/pyyaml/issues/601

**Comment by nmcclaran** [comment]
I had this same issue as well.  It can be bypassed by using the  --use-deprecated=legacy-resolver in pip, although I don't know yet if 6.0.1 breaks cafeteria or if it is a dependency issue.

**Comment by smsajjadzaidi** [comment]
yes, there are some hacks to install pyyaml 5.4.1 but I guess sooner or later, we would need to update cafeteria to support pyyaml >6.0

**Comment by abn** [comment]
@nmcclaran @smsajjadzaidi apologies for the long delay. However, the new version 0.22.1 should allow for PyYAML 6 and work with the new pip resolver.
